Following Filter
beatmaps-io/beatsaver-main pull request #319
Opened 2024-04-10 15:54 UTC by Specture7

RePR from the last one

2024-04-10 15:55 UTC, TCJenkins commented
Can one of the admins verify this patch?

2024-04-10 16:16 UTC, Top-Cat requested changes

2024-04-10 16:16 UTC, Top-Cat commented on src/jvmMain/kotlin/io/beatmaps/api/search.kt
> +                requireAuthorization { _, user ->
This shouldn't be a call to requireAuthorization, it very much seems that when not logged in you just ignore the property.
The call has the side effect of returning an error to the user when not logged in.

Just wrap the whole handler in optionalAuthorization and check if the user is null / auth type is None

2024-04-10 16:16 UTC, Top-Cat commented on src/jvmMain/kotlin/io/beatmaps/api/search.kt
> +                requireAuthorization { _, user ->
(Which will mean you won't need those changes to `requireAuthorization` and `optionalAuthorization`)

2024-04-10 16:16 UTC, Top-Cat commented
But ok to test

2024-04-12 13:31 UTC, Specture7 commented
Should be good now

2024-04-12 14:05 UTC, Top-Cat commented on src/jvmMain/kotlin/io/beatmaps/api/search.kt
> +                                .toInt(16) and (Beatmap.deletedAt.isNull())
That's a whacky place to add a linebreak (does it even need one?)

2024-04-12 14:05 UTC, Top-Cat commented on src/jvmMain/kotlin/io/beatmaps/api/search.kt
> +                                                        Difficulty,
How small is your screen? 🙈

2024-04-12 16:33 UTC, Specture7 commented
fixed the style a bit, i hope this one is good

2024-04-18 07:51 UTC, merged